runtime: python310
service: flask-service
entrypoint: gunicorn -w 2 -b :$PORT main:app

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_instances: 5
  min_instances: 1

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
    secure: always

env_variables:
  FLASK_ENV: prod
  SECRET_KEY: 'kassymshamssym'
